version: '3'
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HTPC_CONFIG_PATH}/sonarr:/config
      - ${HTPC_DOWNLOAD_PATH}:/downloads
      - ${HTPC_MEDIA_PATH}/tvshows:/tv
    depends_on:
      - vpn

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HTPC_CONFIG_PATH}/radarr:/config
      - ${HTPC_DOWNLOAD_PATH}:/downloads
      - ${HTPC_MEDIA_PATH}/movies:/movies
    depends_on:
      - vpn

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${HTPC_CONFIG_PATH}/prowlarr:/config
    depends_on:
      - vpn

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${HTPC_CONFIG_PATH}/bazarr:/config
      - ${HTPC_MEDIA_PATH}/movies:/movies
      - ${HTPC_MEDIA_PATH}/tvshows:/tv
    depends_on:
      - vpn

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${HTPC_CONFIG_PATH}/deluge:/config
      - ${HTPC_DOWNLOAD_PATH}:/downloads
    depends_on:
      - vpn

  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 6767:6767 # Bazarr
      - 7878:7878 # Radarr
      - 8112:8112 # Deluge
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      # - 8787:8787 # Readarr
      # - 9117:9117 # Jackett
    restart: always
    volumes:
      - ${HTPC_CONFIG_PATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${WG_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WG_ADDRESSES}
      - SERVER_CITIES=${WG_SERVER_CITIES}
