version: '3'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER}
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_MEDIA_PATH}/tvshows:/data/tvshows
      - ${JELLYFIN_MEDIA_PATH}/movies:/data/movies
      - ${JELLYFIN_MEDIA_PATH}/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
    restart: unless-stopped
